import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AccessibilityProvider } from "./context/AccessibilityContext";
import { ThemeProvider } from "next-themes"
import TopbarServer from "./components/topbar/TopbarServer";
import { SessionProvider } from "next-auth/react";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AccessibilityProvider>
            <ThemeProvider
              attribute="class"
              themes={["light", "dark", "blue", "green", "purple"]}
              defaultTheme="light"
            >
              {children}
            </ThemeProvider>
          </AccessibilityProvider>
        </Providers>
      </body>
    </html>
  );
}