import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AccessibilityProvider } from "./context/AccessibilityContext";
import { ThemeProvider } from "next-themes"
import TopbarServer from "./components/topbar/TopbarServer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AccessibilityProvider>
          <ThemeProvider
            attribute="class"
            themes={["light", "dark", "blue", "green", "purple"]}
            defaultTheme="light"
          >
            {children}
          </ThemeProvider>
        </AccessibilityProvider>
      </body>
    </html>
  );
}
